version: '3'
services:
  nodejs-server:
    build:
      context: ./server
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./server:/usr/src/app/api
       - /usr/src/app/api/node_modules
  react-ui:
    build:
      context: ./react-ui
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./react-ui:/usr/src/app/react-ui
       - /usr/src/app/react-ui/node_modules