version: '3'

services:

  node-api:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
       - ./server:/usr/app
       - /usr/app/node_modules

  react-client:
    build:
      context: ./react-client
    ports:
      - "5173:5173"
    stdin_open: true
    volumes:
       - ./react-client:/usr/app
       - /usr/app/node_modules